spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  datasource:
    url: jdbc:mysql://localhost:3306/world?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
logging:
  level:
    graphql: DEBUG
